# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

<%
  Rails.application.config.before_configuration do
    env_file = File.join(Rails.root, '.env.yml')
    YAML.load(File.open(env_file)).each do |key, value|
      ENV[key.to_s] = value
    end if File.exists?(env_file)
  end
%>

development:
  admin_name: First Userasdasdf
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["SPECPLAST_GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["SPECPLAST_GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: d9a5232c3ff6267b8d4ea9d13650c1d42364a58698f4ca5ff5d7876b1cb10acf41e10894361252251983469233538409f7f0f4c4c151754a6258f832efbd5ead

test:
  domain_name: localhost:3000
  secret_key_base: 61162e4b88d1ef9b0e7e2deb8194699222d547680d8923e2463cd1a9ec3d4627708ea5291a4ce78566e6f883cc855520d4f1abb23bcc255b4b6f7bfa469745e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["SPECPLAST_ADMIN_NAME"] %>
  admin_email: <%= ENV["SPECPLAST_ADMIN_EMAIL"] %>
  admin_password: <%= ENV["SPECPLAST_ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["SPECPLAST_GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["SPECPLAST_GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["SPECPLAST_PRODUCTION_DOMAIN_NAME"] %>
  secret_token: <%= ENV["SPECPLAST_PRODUCTION_SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SPECPLAST_PRODUCTION_SECRET_KEY_BASE"] %>
